const tilesetmap = {
    1: "grass",
    2: "overgrowngrass",
    3: "grass with flowers",
    4: "yellow tree top",
    5: "green tree top",
    6: "shrub",
    7: "shrub topleft",
    8: "shrub top",
    9: "shrub topright",
    10: "yellow shrub topleft",
    11: "yellow shrub top",
    12: "yellow shrub topright",
    13: "dirt path topleft",
    14: "dirt path top",
    15: "dirt path topright",
    16: "yellow tree bottom",
    17: "green tree bottom",
    18: "small plant",
    19: "shrub left",
    20: "shrub center",
    21: "shrub right",
    22: "yellow shrub left",
    23: "yellow shrub center",
    24: "yellow shrub right",
    25: "dirt path left",
    26: "dirt path center",
    27: "dirt path right",
    28: "small yellow shrub",
    29: "small shrub",
    30: "red mushroom",
    31: "shrub bottomleft",
    32: "shrub bottom",
    33: "shrub bottomright",
    34: "yellow shrub bottom left",
    35: "yellow shrub bottom",
    36: "yellow shrub bottom right",
    37: "dirt path bottom left",
    38: "dirt path bottom",
    39: "dirt path bottom right",
    40: "dirt path inner top left",
    41: "dirt path inner top right",
    42: "dirt path inner bottom right",
    43: "dirt path inner bottom left",
    44: "stone path",
    45: "fence top left",
    46: "fence top",
    47: "fence top right",
    48: "fence top edge",
    49: "grey roof top left",
    50: "grey roof top",
    51: "grey roof top right",
    52: "grey roof chimney",
    53: "red roof top left",
    54: "red roof top",
    55: "red roof top right",
    56: "red roof chimney",
    57: "fence left",
    58: "wheelbarrow",
    59: "fence right",
    60: "fence edge center",
    61: "grey roof bottom left",
    62: "grey roof bottom",
    63: "grey roof bottom right",
    64: "grey roof point",
    65: "red roof bottom left",
    66: "red roof bottom",
    67: "red roof bottom right",
    68: "red roof point",
    69: "fence bottom left",
    70: "fence open",
    71: "fence bottom right",
    72: "fence bottom edge",
    73: "brown house left",
    74: "brown house center",
    75: "brown house door open",
    76: "brown house right",
    77: "grey house left",
    78: "grey house center",
    79: "grey house door open",
    80: "grey house right",
    81: "fence edge left",
    82: "fence edge straight",
    83: "fence edge right",
    84: "sign",
    85: "brown house window",
    86: "brown house door closed",
    87: "brown house door double left",
    88: "brown house door double right",
    89: "grey house window",
    90: "grey house door closed",
    91: "grey house door double left",
    92: "grey house door double right",
    93: "well top", "94": "coin",
    95: "beehive",
    96: "target",
    97: "castle roof top left",
    98: "castle roof top",
    99: "castle roof top right",
    100: "castle roof edge left",
    101: "castle roof edge center",
    102: "castle roof edge right",
    103: "castle roof single",
    104: "ladder",
    105: "well bottom",
    106: "bomb",
    107: "log",
    108: "bag",
    109: "castle roof left",
    110: "castle roof center",
    111: "castle roof right",
    112: "castle gate top left",
    113: "castle gate top right",
    114: "castle open top left",
    115: "castle open top right",
    116: "pickaxe",
    117: "pitchfork",
    118: "key",
    119: "bow",
    120: "arrow",
    121: "castle roof bottom left",
    122: "castle roof bottom center",
    123: "castle roof bottom right",
    124: "castle gate left",
    125: "castle gate right",
    126: "castle window",
    127: "castle wall",
    128: "axe",
    129: "shovel",
    130: "sickle",
    131: "bucket empty",
    132: "bucket full",

    "categories": [
        "ground", "tree", "shrub", "path", "fence", "house roof", "object", "house", "castle wall", "castle roof"
    ]
}

export {tilesetmap};
